### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by PhMueller** [automl/HPOBench#108]
When using python >=3.8, the xgboost benchmark throws the following error: 

ValueError: unsupported pickle protocol: 5

This happens because somehow the openml data is now pickle with protocol 5, which is not supported by python 3.7-pickle inside the container. 

I will investigate this more thoroughly later. 

``` 
[ERROR] BenchmarkServer at 2021-07-05 16:30:49,428 --- unsupported pickle protocol: 5
Traceback (most recent call last):
  File "/home/HPOBench/hpobench/container/server_abstract_benchmark.py", line 58, in init_benchmark
    self.benchmark = Benchmark(**kwargs)  # noqa: F821
  File "/home/philipp/Dokumente/Code/HPOBench/hpobench/benchmarks/ml/xgboost_benchmark.py", line 78, in __init__
    self.get_data()
  File "/home/philipp/Dokumente/Code/HPOBench/hpobench/benchmarks/ml/xgboost_benchmark.py", line 119, in get_data
    x_train, y_train, x_val, y_val, x_test, y_test = data_manager.load()
  File "/home/philipp/Dokumente/Code/HPOBench/hpobench/util/openml_data_manager.py", line 162, in load
    self.X_train, self.y_train, self.X_test, self.y_test, self.variable_types, self.name = _load_data(self.task_id)
  File "/home/philipp/Dokumente/Code/HPOBench/hpobench/util/openml_data_manager.py", line 76, in _load_data
    task = openml.tasks.get_task(task_id)
  File "/usr/local/lib/python3.7/site-packages/openml/utils.py", line 356, in safe_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/openml/tasks/functions.py", line 380, in get_task
    raise e
  File "/usr/local/lib/python3.7/site-packages/openml/tasks/functions.py", line 363, in get_task
    dataset = get_dataset(task.dataset_id, download_data)
  File "/usr/local/lib/python3.7/site-packages/openml/utils.py", line 356, in safe_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/openml/datasets/functions.py", line 530, in get_dataset
    description, features, qualities, arff_file
  File "/usr/local/lib/python3.7/site-packages/openml/datasets/functions.py", line 1023, in _create_dataset_from_description
    qualities=qualities,
  File "/usr/local/lib/python3.7/site-packages/openml/datasets/dataset.py", line 183, in __init__
    self.data_pickle_file = self._create_pickle_in_cache(data_file)
  File "/usr/local/lib/python3.7/site-packages/openml/datasets/dataset.py", line 406, in _create_pickle_in_cache
    data, categorical, attribute_names = pickle.load(fh)
ValueError: unsupported pickle protocol: 5
```  

It also seems that the first few function calls are not inside the container but inside my local python environment.

**Comment by PhMueller** [comment]
I have updated the svm and Xgboost benchmark. They use now Python3.8 instead of 3.7. 
That removes the error.
