### ISSUE TITLE
PyBNN benchmark container error when running

### ISSUE THREAD

**Issue by Game4Move78** [automl/HPOBench#180]
I get an import error at line [client_abstract_benchmark.py:335](https://github.com/automl/HPOBench/blob/47bf141f79e6bdfb26d1f1218b5d5aac09d7d2ce/hpobench/container/client_abstract_benchmark.py#L335) when launching the BNNOnBostonHousing singularity container.

```
[2023-06-06 17:29:46,453][BenchmarkClient][INFO] - ~~~ HPOBENCH VERSION: 0.0.11dev ~~~~ CONTAINER VERSION: 0.0.4 ~~~
Traceback (most recent call last):
  File "/home/HPOBench/hpobench/container/server_abstract_benchmark.py", line 131, in <module>
    exec(f"from hpobench.benchmarks.{args.importBase} import {args.benchmark} as Benchmark")
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/hpobench/benchmarks/ml/__init__.py", line 1, in <module>
    from hpobench.benchmarks.ml.histgb_benchmark import HistGBBenchmark, HistGBBenchmarkBB, HistGBBenchmarkMF
  File "/usr/local/lib/python3.7/site-packages/hpobench/benchmarks/ml/histgb_benchmark.py", line 15, in <module>
    from sklearn.experimental import enable_hist_gradient_boosting  # noqa
ModuleNotFoundError: No module named 'sklearn
```

**Comment by Neeratyoy** [comment]
Hi,
Thanks for bringing this up.
We too noticed the issue and have been looking into a fix. 
The containers will be updated soon (hopefully in a week) which should fix it. 
In the meantime, perhaps the non-container version of the benchmark works for your use case.
